name: myapp

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Place API Key
        run: |
          mkdir -p ~/.private_keys
          echo "${{ secrets.APP_STORE_API_KEY }}" > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8
          ls -la ~/.private_keys/
      - name: Download IPA From URL
        run: |
          curl -L -o myapp.ipa http://web5.ffxia.zhaohaohuo.cc/1048_514/v300_29341048514.ipa
          ls -la myapp.ipa
      - name: Upload to App Store
        run: |
          xcrun altool --upload-app \
            -f "./myapp.ipa" \
            -t ios \
            --apiKey "${{ secrets.APP_STORE_API_KEY_ID }}" \
            --apiIssuer "${{ secrets.APP_STORE_API_ISSUER_ID }}"

      - name: Cleanup
        if: always()
        run: rm -f ~/.private_keys/AuthKey_${{ secrets.APP_STORE_API_KEY_ID }}.p8
